<a href="https://colab.research.google.com/github/ahmedshuvo969/Impace-Learning-comparision-with-kaggle-datasets/blob/master/impact(classication).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [0]:
# Importing the dataset
dataset = pd.read_csv('pima-indians-diabetes.csv')
print(dataset)


      6  148  72  35    0  33.6  0.627  50  1
0     1   85  66  29    0  26.6  0.351  31  0
1     8  183  64   0    0  23.3  0.672  32  1
2     1   89  66  23   94  28.1  0.167  21  0
3     0  137  40  35  168  43.1  2.288  33  1
4     5  116  74   0    0  25.6  0.201  30  0
..   ..  ...  ..  ..  ...   ...    ...  .. ..
762  10  101  76  48  180  32.9  0.171  63  0
763   2  122  70  27    0  36.8  0.340  27  0
764   5  121  72  23  112  26.2  0.245  30  0
765   1  126  60   0    0  30.1  0.349  47  1
766   1   93  70  31    0  30.4  0.315  23  0

[767 rows x 9 columns]


In [0]:
X = dataset.iloc[:, 0:8].values
y = dataset.iloc[:, 8].values

In [0]:
print(X[0])
print(y[0])

[ 1.    85.    66.    29.     0.    26.6    0.351 31.   ]
0


In [0]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)


In [0]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [0]:
# Fitting Random Forest Classification to the Training set
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [0]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [0]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import f1_score
f1 = f1_score(y_test, y_pred, average='macro')
cm1 = (cm[0][0]+cm[1][1])/(cm[0][0]+cm[1][1]+cm[0][1]+cm[1][0])
print("cm = ", cm1)
print("f1 = ", f1)

cm =  0.7467532467532467
f1 =  0.6996249062265566


In [0]:
X_train[0]

array([ 0.06649666,  1.92987383, -3.48834088, -1.30832879, -0.69078054,
       -0.47057917, -0.76640618,  0.23925174])

In [0]:
y1 = X_train[:, 0]
y2 = X_train[:, 1]
y3 = X_train[:, 2]
y4 = X_train[:, 3]
y5 = X_train[:, 4]
y6 = X_train[:, 5]
y7 = X_train[:, 6]
y8 = X_train[:, 7]


In [0]:
print(y8[0])

0.23925173791884083


In [0]:
yt1 = X_test[:, 0]
yt2 = X_test[:, 1]
yt3 = X_test[:, 2]
yt4 = X_test[:, 3]
yt5 = X_test[:, 4]
yt6 = X_test[:, 5]
yt7 = X_test[:, 6]
yt8 = X_test[:, 7]


In [0]:



from scipy.optimize import curve_fit

def test_func1(X, a, b, c, d, e, f, g, h, i, j):
    y1, y2, y3, y4, y5, y6, y7, y8 = X

    return ((1/(b))*(a-c*y1-d*y2-e*y3-f*y4-g*y5-h*y6-i*y7-j*y8)) 
p0 = [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]        # initial guesses
c,cov = curve_fit(test_func1, (y1, y2, y3, y4, y5, y6, y7, y8), y_train, p0)  # fit model




In [0]:
yx = test_func1((yt1, yt2, yt3, yt4, yt5, yt6, yt7, yt8),c[0],c[1],c[2],c[3],c[4],c[5],c[6], c[7],c[8],c[9])


In [0]:
mi = 1
mx = 0
su = 0
for i in range(len(yx)):
  if yx[i]>mx:
    mx = yx[i]
  if yx[i]<mi:
    mi = yx[i]
  su = su + yx[i]
print(mx, mi, (mx + mi), su/len(yx))

0.9548789030482877 -0.5211596475298211 0.4337192555184666 0.330150670622685


In [0]:
t_data = []
for i in range(len(yx)):
  if yx[i]>0.4:
    t_data.append(1)
  else:
    t_data.append(0)



In [0]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, t_data)
from sklearn.metrics import f1_score
f1 = f1_score(y_test, t_data, average='macro')
cm1 = (cm[0][0]+cm[1][1])/(cm[0][0]+cm[1][1]+cm[0][1]+cm[1][0])
print("cm = ", cm1)
print(cm)
print("f1 = ", f1)

cm =  0.7857142857142857
[[85 16]
 [17 36]]
f1 =  0.7615763546798029


In [0]:
# Fitting Kernel SVM to the Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [0]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import f1_score
f1 = f1_score(y_test, y_pred, average='macro')
cm1 = (cm[0][0]+cm[1][1])/(cm[0][0]+cm[1][1]+cm[0][1]+cm[1][0])
print("cm = ", cm1)
print("f1 = ", f1)

cm =  0.7727272727272727
f1 =  0.7196650543506528


In [0]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)


In [0]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import f1_score
f1 = f1_score(y_test, y_pred, average='macro')
cm1 = (cm[0][0]+cm[1][1])/(cm[0][0]+cm[1][1]+cm[0][1]+cm[1][0])
print("cm = ", cm1)
print("f1 = ", f1)

cm =  0.8051948051948052
f1 =  0.7778846153846153


In [0]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [0]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import f1_score
f1 = f1_score(y_test, y_pred, average='macro')
cm1 = (cm[0][0]+cm[1][1])/(cm[0][0]+cm[1][1]+cm[0][1]+cm[1][0])
print("cm = ", cm1)
print("f1 = ", f1)

cm =  0.7792207792207793
f1 =  0.7397096838337641


In [0]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)



# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [0]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import f1_score
f1 = f1_score(y_test, y_pred, average='macro')
cm1 = (cm[0][0]+cm[1][1])/(cm[0][0]+cm[1][1]+cm[0][1]+cm[1][0])
print("cm = ", cm1)
print("f1 = ", f1)

cm =  0.7532467532467533
f1 =  0.7055152979066024


In [0]:
# Fitting Decision Tree Classification to the Training set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)


In [0]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import f1_score
f1 = f1_score(y_test, y_pred, average='macro')
cm1 = (cm[0][0]+cm[1][1])/(cm[0][0]+cm[1][1]+cm[0][1]+cm[1][0])
print("cm = ", cm1)
print("f1 = ", f1)

cm =  0.7467532467532467
f1 =  0.7097288676236044


In [0]:
cm1 = (cm[0][0]+cm[1][1])/(cm[0][0]+cm[1][1]+cm[0][1]+cm[1][0])
print(cm)

[[99 32]
 [34 27]]
